version: '3.9'

services:
  
  coordinator-db:
    image: postgres:latest
    restart: always
    container_name: coordinator-db
    environment:
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
      POSTGRES_DATABASE: pipeline
      POSTGRES_USER: pipeline
    volumes:
      - ./storage/postgres:/var/lib/postgresql
      - ./storage/postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pipeline"]
      interval: 5s
      timeout: 5s
      retries: 5

  # coordinator-db-admin:
  #   container_name: coordinator-db-admin
  #   image: dpage/pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=user@test.com
  #     - PGADMIN_DEFAULT_PASSWORD=test
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     coordinator-db:
  #       condition: service_healthy
  
  coordinator:
    container_name: coordinator
    depends_on:
      coordinator-db:
        condition: service_healthy
    build: ./Coordinator
    volumes:
      - ./Coordinator:/app
      - ./storage/files:/storage/files
      - ./storage/uploads:/storage/uploads
    ports:
      - "5000:5000"
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:5000/health || exit 1
      interval: 60s
      timeout: 15s
      retries: 3
      start_period: 10s
  
  frontender:
    build: ./Frontender
    ports:
      - "3000:3000"

  identifier:
    build: ./Identifier
    restart: unless-stopped
    depends_on:
      coordinator:
        condition: service_healthy
  
  housekeeper:
    build: ./Housekeeper
    restart: unless-stopped
    depends_on:
      coordinator:
        condition: service_healthy
  
  update-cataloger:
    build: ./UpdateCataloger
    volumes:
      - ./UpdateCataloger:/catalogUpdater/
    depends_on:
      coordinator:
        condition: service_healthy
